CREATE TABLE `org_place_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OBJID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ISMAIN` decimal(65,30) NULL DEFAULT NULL COMMENT '判断是否是主要地址',
`NAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
`NATIONID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '必填',
`NATIONNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '必填',
`AREAID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '必填',
`AREANAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '必填',
`POSITIONID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '必填',
`POSITIONNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '必填',
`BDID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`BDNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
`BDFLOORID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`BDFLOORNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
`BDWARDID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`BDWARDNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
`BDROOMID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`BDROOMNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
`MEMO` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
`ORDERNUM` decimal(65,30) NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
INDEX `FK_ORG_PLACE` (`OBJID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '单位的地址。需要考虑：既有像301医院一样，单位地址一个区域，也有像其他小公司一样，只是一个区域内一个楼中的一个房间。'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `org_role_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`ORGID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ROLEID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
INDEX `INDEX_ORG_ROLE_OBJID` (`ORGID` ASC) USING BTREE,
INDEX `INDEX_ORG_ROLE_ROLEID` (`ROLEID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '组织的角色'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `org_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '内部标识',
`CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '组织代号：可以采用编码的形式',
`NAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '组织名称',
`ABBNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '组织简称',
`ORGTYPE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '组织类型：COMP（公司）、DEPT（部门）、GROUP（组）、POSITION（位置，如一楼机房）',
`GRADE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '组织级别',
`CREATTIME` date NULL DEFAULT NULL COMMENT '添加时间',
`ORDERNUM` decimal(65,30) NULL DEFAULT NULL COMMENT '排序',
`STATUS` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '状态:1. 编写  2. 提交  3. 生效   4. 修改  5. 失效',
`MEMO` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '备注',
`PARENTID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
INDEX `INDEX_ORG_ORGTYPE` (`ORGTYPE` ASC) USING BTREE,
INDEX `INDEX_ORG_PARENTID` (`PARENTID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '组织（公司）的资源信息，是一个远大于系统组织的组织（公司）库'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `role_group` (
`id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`ROLEID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`OBJID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
INDEX `FK_ROLEGROUP_ROLE` (`ROLEID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `role_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '角色代号',
`NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '角色名称',
`GRADE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '角色级别',
`ISSYSTEM` decimal(65,30) NULL DEFAULT NULL COMMENT '是否是系统参数',
`SOURCE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '来源：impfromavidm、selfdef',
`MEMO` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '备注',
`DEFAULT_URI` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '登录后默认打开的url',
PRIMARY KEY (`ID`) 
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '角色'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `user_address_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '当前用户联系地址',
`OBJID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '类型：户籍所在地、现住址',
`NATION` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '国家',
`PROVINCE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '省或者州',
`CITY` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '市或者县',
`ADDRESS` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '完整地址',
`BUILDING` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '楼',
`FLOOR` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '层',
`AREA` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '单元/病区',
`ROOM` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '室/房间',
`ORDERNUM` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) 
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '组织的居住地信息'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `user_contact_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '人员联系方式',
`OBJID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用户的标识',
`NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '类型：(1)MOBILE手机、(2)PHOTO电话、(3)EMAIL邮件、(4)QQ (5)MSN (6)WECHAT/(7)EMERGENCY电话、',
`SHOWVAL` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '显示名称',
`VALUE` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '联系方式的内容（值）',
`PRI` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '级别：MAIN（主要的）',
`MEMO` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '备注',
`CREATETIME` date NULL DEFAULT NULL COMMENT '创建时间',
`ORDERNUM` decimal(65,30) NULL DEFAULT NULL COMMENT '排序用',
PRIMARY KEY (`ID`) ,
INDEX `INDEX_USER_CONTACT_NAME` (`NAME` ASC) USING BTREE,
INDEX `FK_USER_CONTRACT` (`OBJID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '联系方式的信息片。是否有权查询相关信息均从此处过来。'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `user_login_history_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`OBJID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`TIME` date NULL DEFAULT NULL,
`LOGINTYPE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
INDEX `FK_USER_LOGIN_HISTORY` (`OBJID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `user_org_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`USERID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ORGID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '单位标识',
PRIMARY KEY (`ID`) ,
INDEX `FK_USER_ORG` (`USERID` ASC) USING BTREE,
INDEX `FK_ORG_USER` (`ORGID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `user_role_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
`USERID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
`ROLEID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
PRIMARY KEY (`ID`) ,
INDEX `FK_USER_ROLE` (`USERID` ASC) USING BTREE,
INDEX `FK_ROLE_USER` (`ROLEID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '人员的角色  ？？'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `user_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '内部标识',
`CODE` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用户代号',
`NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '用户姓名',
`ABBNAME` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '简称、称谓',
`BIRTHDAY` date NULL DEFAULT NULL,
`GENDER` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '性别',
`MEMO` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '备注',
`CREATETIME` date NOT NULL,
`STATUS` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '状态（A：活动、F：冻结、E：编辑）',
`ISSYSUSER` decimal(65,30) NULL DEFAULT 1.000000000000000000000000000000 COMMENT '是否为系统用户：1（系统用户）  0（系统外用户）',
`ISTEMP` decimal(65,30) NULL DEFAULT NULL COMMENT '1标识为临时用户（一般用户通过人员选择界面添加的用户将标记为临时用户）',
PRIMARY KEY (`ID`) ,
INDEX `INDEX_USER_ISSYSUSER` (`ISSYSUSER` ASC) USING BTREE,
INDEX `INDEX_USER_NAME` (`NAME` ASC) USING BTREE,
INDEX `INDEX_USER_STATUS` (`STATUS` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '人员的资源信息，是一个远大于系统用户的用户库'
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;
CREATE TABLE `user_work_tab` (
`ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '人员就读或工作履历',
`OBJID` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '人员ID',
`STARTTIME` date NULL DEFAULT NULL COMMENT '入职时间',
`ENDTIME` date NULL DEFAULT NULL COMMENT '离职时间',
`COMPANY` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '公司名称',
`LOCATION` varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '公司地址',
`ROLE` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '职务',
`DEPT` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '部门',
PRIMARY KEY (`ID`) ,
INDEX `FK_USER_WORK` (`OBJID` ASC) USING BTREE
)
ENGINE = InnoDB
AUTO_INCREMENT = 0
AVG_ROW_LENGTH = 0
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
KEY_BLOCK_SIZE = 0
MAX_ROWS = 0
MIN_ROWS = 0
ROW_FORMAT = Dynamic;

ALTER TABLE `org_place_tab` ADD CONSTRAINT `FK_ORG_PLACE` FOREIGN KEY (`OBJID`) REFERENCES `org_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `org_role_tab` ADD CONSTRAINT `FK_ORG_ROLE` FOREIGN KEY (`ORGID`) REFERENCES `org_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `org_role_tab` ADD CONSTRAINT `FK_ROLE_ORG` FOREIGN KEY (`ROLEID`) REFERENCES `role_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `role_group` ADD CONSTRAINT `FK_ROLEGROUP_ROLE` FOREIGN KEY (`ROLEID`) REFERENCES `role_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_address_tab` ADD CONSTRAINT `FK_USER_ADDRESS` FOREIGN KEY (`ID`) REFERENCES `user_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_contact_tab` ADD CONSTRAINT `FK_USER_CONTRACT` FOREIGN KEY (`OBJID`) REFERENCES `user_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_login_history_tab` ADD CONSTRAINT `FK_USER_LOGIN_HISTORY` FOREIGN KEY (`OBJID`) REFERENCES `user_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_org_tab` ADD CONSTRAINT `FK_ORG_USER` FOREIGN KEY (`ORGID`) REFERENCES `org_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_org_tab` ADD CONSTRAINT `FK_USER_ORG` FOREIGN KEY (`USERID`) REFERENCES `user_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_role_tab` ADD CONSTRAINT `FK_ROLE_USER` FOREIGN KEY (`ROLEID`) REFERENCES `role_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_role_tab` ADD CONSTRAINT `FK_USER_ROLE` FOREIGN KEY (`USERID`) REFERENCES `user_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `user_work_tab` ADD CONSTRAINT `FK_USER_WORK` FOREIGN KEY (`OBJID`) REFERENCES `user_tab` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT;

